steps:
  - name: maven:3.6-jdk-11
    entrypoint: mvn
    args: ['clean', 'install', '-B', '-q']

  - name: maven:3.6-jdk-11
    entrypoint: mvn
    args: ['package', '-B', '--file', 'google-cloud-graalvm-samples/']
