steps:
  - name: oracle/graalvm-ce:20.1.0-java11
    entrypoint: bash
    args: ['./.cloudbuild/graal-build-script.sh']

  - name: oracle/graalvm-ce:20.1.0-java11
    args: ['./google-cloud-graalvm-samples/pubsub-sample/target/com.example.pubsubsampleapplication']

options:
  # Need to specify a better machine to avoid OOM errors.
  machineType: 'N1_HIGHCPU_32'
