steps:
  # Build the sample images
  - name: oracle/graalvm-ce:20.2.0-java11
    entrypoint: bash
    args: ['./.cloudbuild/graal-build-script.sh']

  # Start emulators
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '-d', '--network=cloudbuild', '--name=spanner-emulator', '-p', '9010:9010', '-p', '9020:9020', 'gcr.io/cloud-spanner-emulator/emulator:1.1.1']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '-d', '--network=cloudbuild', '--name=firestore-emulator', 'google/cloud-sdk', 'sh', '-c', 'gcloud beta emulators firestore start --host-port=0.0.0.0:9010']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '-d', '--network=cloudbuild', '--name=bigtable-emulator', 'google/cloud-sdk', 'sh', '-c', 'gcloud beta emulators bigtable start --host-port=0.0.0.0:9010']
  # Wait for emulators to start
  - name: jwilder/dockerize:0.6.1
    args: ['dockerize', '-timeout=40s', '-wait=tcp://spanner-emulator:9010', '-wait=tcp://firestore-emulator:9010', '-wait=tcp://bigtable-emulator:9010']


  # Run the tests
  - name: oracle/graalvm-ce:20.2.0-java11
    args: ['./google-cloud-graalvm-samples/graalvm-samples-client-library/bigquery-sample/target/com.example.bigquerysampleapplication']

  - name: oracle/graalvm-ce:20.2.0-java11
    args: ['./google-cloud-graalvm-samples/graalvm-samples-client-library/pubsub-sample/target/com.example.pubsubsampleapplication']

  - name: oracle/graalvm-ce:20.2.0-java11
    args: ['./google-cloud-graalvm-samples/graalvm-samples-client-library/storage-sample/target/com.example.storagesampleapplication']

  - name: oracle/graalvm-ce:20.2.0-java11
    args: ['./google-cloud-graalvm-samples/graalvm-samples-client-library/logging-sample/target/com.example.loggingsampleapplication']

  - name: oracle/graalvm-ce:20.2.0-java11
    args: ['./google-cloud-graalvm-samples/graalvm-samples-client-library/secretmanager-sample/target/com.example.secretmanagersampleapplication']

  - name: oracle/graalvm-ce:20.2.0-java11
    args: ['./google-cloud-graalvm-samples/graalvm-samples-client-library/trace-sample/target/com.example.tracesampleapplication']

  - name: oracle/graalvm-ce:20.2.0-java11
    args: ['./google-cloud-graalvm-samples/graalvm-samples-client-library/firestore-sample/target/com.example.firestoresampleapplication']
    env:
      - 'FIRESTORE_EMULATOR_HOST=firestore-emulator:9010'

  - name: oracle/graalvm-ce:20.2.0-java11
    args: ['./google-cloud-graalvm-samples/graalvm-samples-client-library/spanner-sample/target/com.example.spannersampleapplication']
    env:
      - 'SPANNER_EMULATOR_HOST=spanner-emulator:9010'

  - name: oracle/graalvm-ce:20.2.0-java11
    args: ['./google-cloud-graalvm-samples/graalvm-samples-client-library/bigtable-sample/target/com.example.bigtablesampleapplication']
    env:
      - 'BIGTABLE_EMULATOR_HOST=bigtable-emulator:9010'

timeout: 1800s # 30 minutes
options:
  # Need to specify a better machine to avoid OOM errors.
  machineType: 'N1_HIGHCPU_32'
