steps:
  # Build the sample images
  - name: ghcr.io/graalvm/graalvm-ce:java11-21.0.0
    id: mvn-install
    entrypoint: bash
    args: ['./.cloudbuild/graal-build-script.sh']

  # Start emulators
  - name: 'gcr.io/cloud-builders/docker'
    id: spanner-emulator
    args: ['run', '-d', '--network=cloudbuild', '--name=spanner-emulator', '-p', '9010:9010', '-p', '9020:9020', 'gcr.io/cloud-spanner-emulator/emulator:1.1.1']
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/docker'
    id: firestore-emulator
    args: ['run', '-d', '--network=cloudbuild', '--name=firestore-emulator', 'google/cloud-sdk', 'sh', '-c', 'gcloud beta emulators firestore start --host-port=0.0.0.0:9010']
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/docker'
    id: bigtable-emulator
    args: ['run', '-d', '--network=cloudbuild', '--name=bigtable-emulator', 'google/cloud-sdk', 'sh', '-c', 'gcloud beta emulators bigtable start --host-port=0.0.0.0:9010']
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/docker'
    id: datastore-emulator
    args: ['run', '-d', '--network=cloudbuild', '--name=datastore-emulator', 'google/cloud-sdk', 'sh', '-c', 'gcloud beta emulators datastore start --host-port=0.0.0.0:9010']
    waitFor: ['-']
  # Wait for emulators to start
  - name: jwilder/dockerize:0.6.1
    args: ['dockerize', '-timeout=40s', '-wait=tcp://spanner-emulator:9010', '-wait=tcp://firestore-emulator:9010', '-wait=tcp://bigtable-emulator:9010', '-wait=tcp://datastore-emulator:9010']
    waitFor: [spanner-emulator, firestore-emulator, datastore-emulator, bigtable-emulator]

  # Run the tests
  - name: ghcr.io/graalvm/graalvm-ce:java11-21.0.0
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ./mvnw package -P graal -f google-cloud-graalvm-samples/graalvm-samples-client-library/bigquery-sample \
        && ./google-cloud-graalvm-samples/graalvm-samples-client-library/bigquery-sample/target/com.example.bigquerysampleapplication
    waitFor: ['-']

#  - name: ghcr.io/graalvm/graalvm-ce:java11-21.0.0
#    entrypoint: 'bash'
#    args:
#      - '-c'
#      - |
#        ./mvnw package -P graal -f google-cloud-graalvm-samples/graalvm-samples-client-library/pubsub-sample/pom.xml \
#        && ./google-cloud-graalvm-samples/graalvm-samples-client-library/pubsub-sample/target/com.example.pubsubsampleapplication
#    waitFor: ['mvn-install']
#
#  - name: ghcr.io/graalvm/graalvm-ce:java11-21.0.0
#    entrypoint: 'bash'
#    args:
#      - '-c'
#      - |
#        ./mvnw package -P graal -f google-cloud-graalvm-samples/graalvm-samples-client-library/storage-sample/pom.xml \
#        && ./google-cloud-graalvm-samples/graalvm-samples-client-library/storage-sample/target/com.example.storagesampleapplication
#    waitFor: ['mvn-install']
#
#  - name: ghcr.io/graalvm/graalvm-ce:java11-21.0.0
#    entrypoint: 'bash'
#    args:
#      - '-c'
#      - |
#        ./mvnw package -P graal -f google-cloud-graalvm-samples/graalvm-samples-client-library/logging-sample/pom.xml \
#        && ./google-cloud-graalvm-samples/graalvm-samples-client-library/logging-sample/target/com.example.loggingsampleapplication
#    waitFor: ['mvn-install']
#
#  - name: ghcr.io/graalvm/graalvm-ce:java11-21.0.0
#    entrypoint: 'bash'
#    args:
#      - '-c'
#      - |
#        ./mvnw package -P graal -f google-cloud-graalvm-samples/graalvm-samples-client-library/secretmanager-sample/pom.xml \
#        && ./google-cloud-graalvm-samples/graalvm-samples-client-library/secretmanager-sample/target/com.example.secretmanagersampleapplication
#    waitFor: ['mvn-install']
#
#  - name: ghcr.io/graalvm/graalvm-ce:java11-21.0.0
#    entrypoint: 'bash'
#    args:
#      - '-c'
#      - |
#        ./mvnw package -P graal -f google-cloud-graalvm-samples/graalvm-samples-client-library/tasks-sample/pom.xml \
#        && ./google-cloud-graalvm-samples/graalvm-samples-client-library/tasks-sample/target/com.example.taskssampleapplication
#    waitFor: ['mvn-install']
#
#  - name: ghcr.io/graalvm/graalvm-ce:java11-21.0.0
#    entrypoint: 'bash'
#    args:
#      - '-c'
#      - |
#        ./mvnw package -P graal -f google-cloud-graalvm-samples/graalvm-samples-client-library/trace-sample/pom.xml \
#        && ./google-cloud-graalvm-samples/graalvm-samples-client-library/trace-sample/target/com.example.tracesampleapplication
#    waitFor: ['mvn-install']
#
#  - name: ghcr.io/graalvm/graalvm-ce:java11-21.0.0
#    entrypoint: 'bash'
#    args:
#      - '-c'
#      - |
#        ./mvnw package -P graal -f google-cloud-graalvm-samples/graalvm-samples-client-library/firestore-sample/pom.xml \
#        && ./google-cloud-graalvm-samples/graalvm-samples-client-library/firestore-sample/target/com.example.firestoresampleapplication
#    env:
#      - 'FIRESTORE_EMULATOR_HOST=firestore-emulator:9010'
#    waitFor: ['mvn-install']
#
#  - name: ghcr.io/graalvm/graalvm-ce:java11-21.0.0
#    entrypoint: 'bash'
#    args:
#      - '-c'
#      - |
#        ./mvnw package -P graal -f google-cloud-graalvm-samples/graalvm-samples-client-library/spanner-sample/pom.xml \
#        && ./google-cloud-graalvm-samples/graalvm-samples-client-library/spanner-sample/target/com.example.spannersampleapplication
#    env:
#      - 'SPANNER_EMULATOR_HOST=spanner-emulator:9010'
#    waitFor: ['mvn-install']
#
#  - name: ghcr.io/graalvm/graalvm-ce:java11-21.0.0
#    entrypoint: 'bash'
#    args:
#      - '-c'
#      - |
#        ./mvnw package -P graal -f google-cloud-graalvm-samples/graalvm-samples-client-library/bigtable-sample/pom.xml \
#        && ./google-cloud-graalvm-samples/graalvm-samples-client-library/bigtable-sample/target/com.example.bigtablesampleapplication
#    env:
#      - 'BIGTABLE_EMULATOR_HOST=bigtable-emulator:9010'
#    waitFor: ['mvn-install']
#
#  - name: ghcr.io/graalvm/graalvm-ce:java11-21.0.0
#    args:
#      - '-c'
#      - |
#        ./mvnw package -P graal -f google-cloud-graalvm-samples/graalvm-samples-client-library/datastore-sample \
#        && ./google-cloud-graalvm-samples/graalvm-samples-client-library/datastore-sample/target/com.example.datastoresampleapplication
#    env:
#      - 'DATASTORE_EMULATOR_HOST=http://datastore-emulator:9010'
#    waitFor: ['mvn-install']

  - name: ghcr.io/graalvm/graalvm-ce:java11-21.0.0
    args: ['./mvnw', 'verify', '-P graal', '-f google-cloud-graalvm-samples/graalvm-samples-quarkus']
    waitFor: ['mvn-install']

  - name: ghcr.io/graalvm/graalvm-ce:java11-21.0.0
    args: ['./mvnw', 'verify', '-P graal', '-f google-cloud-graalvm-samples/graalvm-samples-spring']
    waitFor: ['mvn-install']

timeout: 3600s # 60 minutes
options:
  # Need to specify a better machine to avoid OOM errors.
  machineType: 'N1_HIGHCPU_32'
