steps:
  - name: openjdk:11-jdk
    entrypoint: bash
    args: ['./mvnw', 'clean', 'install', 'package', '-B', '-q']

  - name: openjdk:11-jdk
    entrypoint: java
    args: ['-jar', 'google-cloud-graalvm-samples/graalvm-samples-client-library/pubsub-sample/target/pubsub-sample-1.0.0-SNAPSHOT.jar']

  - name: openjdk:11-jdk
    entrypoint: java
    args: ['-jar', 'google-cloud-graalvm-samples/graalvm-samples-client-library/storage-sample/target/storage-sample-1.0.0-SNAPSHOT.jar']

  - name: openjdk:11-jdk
    entrypoint: java
    args: ['-jar', 'google-cloud-graalvm-samples/graalvm-samples-client-library/logging-sample/target/logging-sample-1.0.0-SNAPSHOT.jar']

  - name: openjdk:11-jdk
    entrypoint: java
    args: ['-jar', 'google-cloud-graalvm-samples/graalvm-samples-client-library/trace-sample/target/trace-sample-1.0.0-SNAPSHOT.jar']

