steps:
  - name: openjdk:11-jdk
    entrypoint: bash
    args: ['./mvnw', 'clean', 'install', 'package', '-B', '-q']

  - name: openjdk:11-jdk
    entrypoint: java
    args: ['-jar', 'google-cloud-graalvm-samples/google-cloud-graalvm-pubsub-sample/target/google-cloud-graalvm-pubsub-sample-1.0.0-SNAPSHOT.jar']
