# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  std-java-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: |
        mvn clean install -B -q
        mvn package -B --file google-cloud-graalvm-samples/

    - name: Run Samples
      run: |
        cd google-cloud-graalvm-samples
        java -jar google-cloud-graalvm-pubsub-sample/target/google-cloud-graalvm-pubsub-sample-1.0.0-SNAPSHOT.jar

  graal-java-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up GraalVM Compiler
      uses: rinx/setup-graalvm-ce@v0.0.4
      with:
        graalvm-version: "20.1.0"
        java-version: "java11"
        native-image: "true"

    - name: Native Image Compile
      run: |
        mvn clean install -B -q
        mvn package -P graal -B --file google-cloud-graalvm-samples/

    - name: Run Samples
      run: |
        cd google-cloud-graalvm-samples
        ./google-cloud-graalvm-pubsub-sample/target/com.example.pubsubsampleapplication
